server:
  port: 8888
  servlet:
    context-path: /

spring:
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sign?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: ##########
    password: ##########
    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化连接大小
    initial-size: 8
    # 最小空闲连接数
    min-idle: 5
    # 最大连接数
    max-active: 64
    # 最大连接等待超时时间
    max-wait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    pool-prepared-statements: true
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false

    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall
  jpa:
    hibernate:
      # 实体类有更新时，数据库表更新
      ddl-auto: update
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect